# Generated by Django 3.1 on 2020-09-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publicationDate', models.DateField()),
                ('authors', models.ManyToManyField(to='todoApp.Author')),
            ],
        ),
    ]
